### ISSUE TITLE
采购模块采购物料冗余字段删除

### ISSUE THREAD

**Issue by Time1ess** [DLUT-SIE/ERP#288]
https://github.com/DLUT-SIE/ERP/blob/2bffa38642efae3dd76fbf905082d7e7a4f09a10/Process/models/quota.py#L73-L99

https://github.com/DLUT-SIE/ERP/blob/8832a171aa54440de7f49a32398e210407a905d1/Procurement/models/procurement.py#L89-L124

`material_number`等字段应予以删除？`count`、`weight`等字段是否应予以保留？

**Comment by MoriatyC** [comment]
随便

**Comment by eyeeco** [comment]
从采购的角度看这个问题建议删除`material_number` 及 `category `字段 
这两个字段在Process->Material的模型上有相同字段
由于两者外键关系，保留冗余需要二者在创建、修改、删除时增大工作量

**Comment by Time1ess** [comment]
删除后可能导致无法访问到必需信息，因此应不修改。
